version: "24.0.6"
services:
  web:
    image: python 3.12.0
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: data_ingestion_script.py

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: docker


